export const REGISTER_USERS = 'REGISTER_USERS'
export const RECIEVED_REGISTER_USERS = 'RECIEVED_REGISTER_USERS'
export const FAILURE_REGISTER_USERS = 'FAILURE_REGISTER_USERS'

export const LOGIN_USERS = 'LOGIN_USERS'
export const RECIEVED_LOGIN_USERS = 'RECIEVED_LOGIN_USERS'
export const FAILURE_LOGIN_USERS = 'FAILURE_LOGIN_USERS'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const RECIEVED_GET_CATEGORIES = 'RECIEVED_GET_CATEGORIES'
export const FAILURE_GET_CATEGORIES = 'FAILURE_GET_CATEGORIES'

export const GET_ALL_BLOGS = 'GET_ALL_BLOGS'
export const RECIEVED_GET_ALL_BLOGS = 'RECIEVED_GET_ALL_BLOGS'
export const FAILURE_GET_ALL_BLOGS = 'FAILURE_GET_ALL_BLOGS'

export const GET_USERS = 'GET_USERS'
export const RECIEVED_GET_USERS = 'RECIEVED_GET_USERS'
export const FAILURE_GET_USERS = 'FAILURE_GET_USERS'

export const GET_USERS_BLOGS = 'GET_USERS_BLOGS'
export const RECIEVED_GET_USERS_BLOGS = 'RECIEVED_GET_USERS_BLOGS'
export const FAILURE_GET_USERS_BLOGS = 'FAILURE_GET_USERS_BLOGS'

export const CREATE_BLOG = 'CREATE_BLOG'
export const RECIEVED_CREATE_BLOG = 'RECIEVED_CREATE_BLOG'
export const FAILURE_CREATE_BLOG = 'FAILURE_CREATE_BLOG'

export const DELETE_BLOG = 'DELETE_BLOG'
export const RECIEVED_DELETE_BLOG = 'RECIEVED_DELETE_BLOG'
export const FAILURE_DELETE_BLOG = 'FAILURE_DELETE_BLOG'

export const GET_BLOG_BY_ID = 'GET_BLOG_BY_ID'
export const RECIEVED_GET_BLOG_BY_ID = 'RECIEVED_GET_BLOG_BY_ID'
export const FAILURE_GET_BLOG_BY_ID = 'FAILURE_GET_BLOG_BY_ID'

export const UPDATE_BLOG = 'UPDATE_BLOG'
export const RECIEVED_UPDATE_BLOG = 'RECIEVED_UPDATE_BLOG'
export const FAILURE_UPDATE_BLOG = 'FAILURE_UPDATE_BLOG'